# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Thonk
    url: https://www.thonk.xyz
  - name: Thonk Minecraft
    url: https://www.thonk.xyz
  - name: Thonk Status Page
    url: https://www.thonk.xyz
  - name: Thonk Cloud
    url: https://www.thonk.cloud
  - name: Sonarr
    url: https://sonarr.thonk.xyz
  - name: Radarr
    url: https://radarr.thonk.xyz
  - name: Transmission
    url: https://transmission.thonk.xyz
    expectedStatusCodes:
      - 200
      - 401
  - name: Netdata
    url: https://netdata.thonk.xyz
  - name: Tautulli
    url: https://tautulli.thonk.xyz
  - name: Files
    url: https://files.thonk.xyz
  - name: Skippy Cloud
    url: $SKIPPY_URL
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.thonk.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Thonk Global Cloud Services Uptime Monitor"
  introMessage: For cloud platform status, see https://status.thonk.xyz. Contact: cloud@thonk.xyz
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
